# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddc8a8508bc5499044372e718e3b94458bc2b04fadcccdf2c37b398ffcc80b84d92180624fd5166dde8e24383f6779a8ec2ed18bbaab85e3f917a81b4ac2e20

test:
  secret_key_base: 3ace6c860948ce6770ec4e17c9e590a8f4e8850e1053b706bf59604cf03315d5aae6d7c548028713ee3db3f26a14ac4a2c2e6d53315d224c0164f47b519b5f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
